export {Observable as O} from "rxjs/Observable"
export {Subject as S} from "rxjs/Subject"
export {ReplaySubject as RS} from "rxjs/ReplaySubject"

// Observable functions
import "rxjs/add/observable/combineLatest"
import "rxjs/add/observable/from"
import "rxjs/add/observable/merge"
import "rxjs/add/observable/of"

// Observable methods
import "rxjs/add/operator/combineLatest"
import "rxjs/add/operator/concat"
import "rxjs/add/operator/distinctUntilChanged"
import "rxjs/add/operator/debounceTime"
import "rxjs/add/operator/delay"
import "rxjs/add/operator/do"
import "rxjs/add/operator/filter"
import "rxjs/add/operator/let"
import "rxjs/add/operator/merge"
import "rxjs/add/operator/mergeMap"
import "rxjs/add/operator/map"
import "rxjs/add/operator/pairwise"
import "rxjs/add/operator/pluck"
import "rxjs/add/operator/sample"
import "rxjs/add/operator/scan"
import "rxjs/add/operator/share"
import "rxjs/add/operator/shareReplay"
import "rxjs/add/operator/startWith"
import "rxjs/add/operator/skip"
import "rxjs/add/operator/take"
import "rxjs/add/operator/throttleTime"
import "rxjs/add/operator/withLatestFrom"

// let Observable = window.O = Observable
